services:

  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Atoolo\Form\Controller\:
    resource: '../src/Controller'

  Atoolo\Form\Service\:
    resource: '../src/Service'

  Atoolo\Form\Processor\:
    resource: '../src/Processor'

  Atoolo\Form\Processor\EmailSender:
    arguments:
      - '@Atoolo\Form\Service\Email\EmailMessageModelFactory'
      - '@Atoolo\Form\Service\Email\EmailHtmlMessageTwigRenderer'
